del "..\Cheddar.js"
echo. >NUL 2>"..\Cheddar.js"
@echo off
type jquery.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type object-watch.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type CheddarUtils.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type DisplayObject.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type DisplayImage.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type DisplayVector.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type Slider.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type Sprite.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type SpriteSheet.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type Button.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type Stage.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type CheddarCore.js >>  "..\Cheddar.js"
echo. >Nul >> "..\Cheddar.js"
type Text.js >>  "..\Cheddar.js"